table '365 customers first use'
	lineageTag: 152b8c03-9234-49fe-99df-d80d0897abda

	column DC_TENANT_ID
		dataType: string
		lineageTag: 0a54e962-2a40-446c-884f-7de33496901c
		summarizeBy: none
		sourceColumn: DC_TENANT_ID

		annotation SummarizationSetBy = Automatic

	column CREATION_DATE_APPROX
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 9a9906dc-2e2b-470b-bafb-52560d1d26cf
		summarizeBy: none
		sourceColumn: CREATION_DATE_APPROX

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: MMMM yyyy
		lineageTag: 6a91ec84-186b-4b8f-8c82-3f9b4530a48e
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	partition '365 customers first use' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Snowflake.Databases("vena-prod.snowflakecomputing.com","PRODUCT_POWER_USER_READ_WH"){[Name="PROD_RAW"]}[Data], "WITH PROD_TENANT_INFO AS#(lf)(#(lf)select#(lf)tenant_id,#(lf)data_cntr_cd#(lf)from PROD_HARMONIZED.PRODUCT.TENANT_PROF#(lf)where CRNT_RCRD_IND = 'Y'#(lf)and tenant_typ_nm in ('PRODUCTION')#(lf)and organization_typ_nm = 'CUSTOMER'#(lf)and tenant_enbld_status_nm = 'ENABLED'#(lf)),#(lf)#(lf)user_info as #(lf)(#(lf)SELECT distinct#(lf)tenant_dc,#(lf)user_id,#(lf)last_impersonation_login_dt,#(lf)case #(lf)    when (last_impersonation_login_dt is not null and admin_access_ind = 'Y' and ntfctn_email is null) then 'Y'#(lf)    end as consultant_login#(lf)FROM PROD_HARMONIZED.PRODUCT.VW_USER_PROF#(lf)where crnt_rcrd_ind = 'Y'#(lf)and actvtn_status_nm = 'ACTIVE'#(lf)order by user_id#(lf))#(lf)#(lf)#(lf)select #(lf)concat(region,'.',customer_id) as dc_tenant_id,#(lf)min(etl_load_date) as creation_date_approx#(lf)#(lf)from PROD_RAW.PROD_TEAM_SANDBOX.VENALYTICS_RUM_DATA_STAGING staging#(lf)inner join prod_tenant_info on staging.customer_id = prod_tenant_info.tenant_id and staging.region = prod_tenant_info.data_cntr_cd#(lf)left join user_info on user_info.tenant_dc = concat(region,'.',customer_id) and user_info.user_id = staging.user_id#(lf)where file_id is not null #(lf)and total_duration is not null#(lf)and is_initial_load = 'TRUE'#(lf)AND ACTION_NAME = 'refresh'#(lf)and consultant_login is null #(lf)#(lf)group by #(lf)concat(region,'.',customer_id)#(lf)having count(total_duration) > 20", null, [EnableFolding=true]),
				    #"Duplicated Column" = Table.DuplicateColumn(Source, "CREATION_DATE_APPROX", "CREATION_DATE_APPROX - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"CREATION_DATE_APPROX - Copy", "Month"}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Renamed Columns",{{"Month", Date.StartOfMonth, type datetime}})
				in
				    #"Calculated Start of Month"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

