table Agg_V365_Vena_Monthly
	lineageTag: 9a16e3dd-410d-49fe-9b13-2a1ed2ce5a05

	column YEAR_MONTH
		dataType: dateTime
		formatString: MMMM yyyy
		lineageTag: a987f9ee-83fe-4bc3-8cc3-cbfdbce8948c
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOTAL_REFRESHES
		dataType: double
		lineageTag: 41a1c719-7a4e-47ff-bb0f-5af5c301a600
		summarizeBy: sum
		sourceColumn: TOTAL_REFRESHES

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REFRESHES_BELOW_8S
		dataType: double
		lineageTag: 391ccbb3-5e24-46ee-ae13-60e3fdc4e759
		summarizeBy: sum
		sourceColumn: REFRESHES_BELOW_8S

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PCT_BELOW_8S
		dataType: double
		lineageTag: e0954ec4-08fb-4de6-8294-7d14e9f1bea5
		summarizeBy: sum
		sourceColumn: PCT_BELOW_8S

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVG_DURATION_SEC
		dataType: double
		lineageTag: 71e87abd-4b23-4ae4-a95a-dd2eee500349
		summarizeBy: sum
		sourceColumn: AVG_DURATION_SEC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P25_DURATION
		dataType: double
		lineageTag: d13b1e60-aa70-408b-b786-0fb9c2774822
		summarizeBy: sum
		sourceColumn: P25_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P50_DURATION
		dataType: double
		lineageTag: 9604426d-60fe-47ef-b038-a3e7356e9798
		summarizeBy: sum
		sourceColumn: P50_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P70_DURATION
		dataType: double
		lineageTag: 9e5f0c9f-23b0-47cd-9140-d48689177277
		summarizeBy: sum
		sourceColumn: P70_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P80_DURATION
		dataType: double
		lineageTag: 3e4735b4-f1b9-45f1-8368-1ec00aa03431
		summarizeBy: sum
		sourceColumn: P80_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P90_DURATION
		dataType: double
		lineageTag: 1d9b5614-e496-43a3-aa61-ca4f2d5911b4
		summarizeBy: sum
		sourceColumn: P90_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P95_DURATION
		dataType: double
		lineageTag: 988c0f57-074b-486b-93ac-ef42605262cf
		summarizeBy: sum
		sourceColumn: P95_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P99_DURATION
		dataType: double
		lineageTag: d72ce362-6618-4bb8-aed6-3196f370d09f
		summarizeBy: sum
		sourceColumn: P99_DURATION

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DISTINCT_TENANTS
		dataType: double
		lineageTag: cf9f4d95-9320-43fd-8809-8760e7af7268
		summarizeBy: sum
		sourceColumn: DISTINCT_TENANTS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DISTINCT_USERS
		dataType: double
		lineageTag: 57f16965-e5ea-4488-a264-ab9a46e863d4
		summarizeBy: sum
		sourceColumn: DISTINCT_USERS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Agg_V365_Vena_Monthly = m
		mode: import
		queryGroup: 'V365 Add-in - Datasets'
		source =
				let
				    Source = Value.NativeQuery(Snowflake.Databases("vena-prod.snowflakecomputing.com","PRODUCT_POWER_USER_READ_WH",[Implementation="2.0"]){[Name="PROD_RAW"]}[Data], "WITH prod_tenant_info AS (#(lf)    SELECT DISTINCT tenant_id, data_cntr_cd#(lf)    FROM PROD_HARMONIZED.PRODUCT.TENANT_PROF#(lf)    WHERE crnt_rcrd_ind = 'Y'#(lf)      AND tenant_typ_nm = 'PRODUCTION'#(lf)      AND organization_typ_nm = 'CUSTOMER'#(lf)      AND tenant_enbld_status_nm = 'ENABLED'#(lf)),#(lf)#(lf)base_data AS (#(lf)    SELECT#(lf)        s.tenant_id,#(lf)        s.user_id,#(lf)        s.total_duration_ms / 1000.0            AS total_duration_sec,#(lf)        DATE_TRUNC('MONTH', s.event_dt)          AS year_month#(lf)    FROM PROD_HARMONIZED.PRODUCT.RUM_DATA_LOG s#(lf)    INNER JOIN prod_tenant_info t#(lf)        ON s.tenant_id = t.tenant_id#(lf)       AND s.data_cntr_cd = t.data_cntr_cd#(lf)    WHERE s.file_id IS NOT NULL#(lf)      AND s.initial_load_ind = 'Y'#(lf)      AND s.action_nm = 'refresh'#(lf)      AND s.total_duration_ms IS NOT NULL#(lf)      AND TO_DATE(s.event_dt) >= CURRENT_DATE - 365#(lf))#(lf)#(lf)SELECT#(lf)    year_month,#(lf)    COUNT(*)                                                                        AS total_refreshes,#(lf)    COUNT(CASE WHEN total_duration_sec <= 8 THEN 1 END)                             AS refreshes_below_8s,#(lf)    ROUND(#(lf)        COUNT(CASE WHEN total_duration_sec <= 8 THEN 1 END)::FLOAT#(lf)        / NULLIF(COUNT(*), 0), 4#(lf)    )                                                                               AS pct_below_8s,#(lf)    ROUND(AVG(total_duration_sec), 4)                                                AS avg_duration_sec,#(lf)    ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p25_duration,#(lf)    ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p50_duration,#(lf)    ROUND(PERCENTILE_CONT(0.70) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p70_duration,#(lf)    ROUND(PERCENTILE_CONT(0.80) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p80_duration,#(lf)    ROUND(PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p90_duration,#(lf)    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p95_duration,#(lf)    ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY total_duration_sec), 4)       AS p99_duration,#(lf)    COUNT(DISTINCT tenant_id)                                                        AS distinct_tenants,#(lf)    COUNT(DISTINCT user_id)                                                          AS distinct_users#(lf)FROM base_data#(lf)GROUP BY year_month#(lf)ORDER BY year_month", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YEAR_MONTH", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

