table Agg_Hydra_SimpleRefresh_Monthly
	lineageTag: 205f8913-ad1d-4284-855a-7fd7a9ac66f1

	column YEAR_MONTH
		dataType: dateTime
		formatString: MMMM yyyy
		lineageTag: dac24806-1e7d-4112-8c89-decc9c2b97d5
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOTAL_REFRESHES
		dataType: int64
		lineageTag: d0302d34-752d-481c-a833-ed010d51da44
		summarizeBy: none
		sourceColumn: TOTAL_REFRESHES

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REFRESHES_BELOW_8S
		dataType: double
		lineageTag: 5d81b6a4-2b68-4686-b173-531e423c4191
		summarizeBy: sum
		sourceColumn: REFRESHES_BELOW_8S

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PCT_BELOW_8S
		dataType: double
		lineageTag: 1f37b89d-6437-445e-9dfd-a2b3b3f82c5f
		summarizeBy: sum
		sourceColumn: PCT_BELOW_8S

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AVG_TIMING
		dataType: double
		lineageTag: 9128b7e3-0641-4521-84d5-118c8e721c69
		summarizeBy: sum
		sourceColumn: AVG_TIMING

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P25_TIMING
		dataType: double
		lineageTag: f6578850-7435-473e-9551-32104c4f32d0
		summarizeBy: none
		sourceColumn: P25_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P50_TIMING
		dataType: double
		lineageTag: 6b6b1b1b-d1d5-4817-8f4b-5e61829e2c6e
		summarizeBy: none
		sourceColumn: P50_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P70_TIMING
		dataType: double
		lineageTag: 00017f60-4766-4ed7-8277-052e5c89eddf
		summarizeBy: none
		sourceColumn: P70_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P80_TIMING
		dataType: double
		lineageTag: b854fd06-12e6-4ed4-8f13-941a8a553c44
		summarizeBy: none
		sourceColumn: P80_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P90_TIMING
		dataType: double
		lineageTag: 7b420798-6660-4cd1-8aa9-eeb41b7870e0
		summarizeBy: none
		sourceColumn: P90_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P95_TIMING
		dataType: double
		lineageTag: 56a6cbd1-0185-4e6d-b407-069d20976f8c
		summarizeBy: none
		sourceColumn: P95_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column P99_TIMING
		dataType: double
		lineageTag: f966bb23-8f82-482d-a43f-1bc26873ce76
		summarizeBy: none
		sourceColumn: P99_TIMING

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DISTINCT_TENANTS
		dataType: double
		lineageTag: 086346d9-79d6-4dbd-9cb7-9622db33a786
		summarizeBy: sum
		sourceColumn: DISTINCT_TENANTS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DISTINCT_USERS
		dataType: double
		lineageTag: fe020352-2d04-4450-b588-5fdc348b3274
		summarizeBy: sum
		sourceColumn: DISTINCT_USERS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Agg_Hydra_SimpleRefresh_Monthly = m
		mode: import
		queryGroup: 'Hydra UI Refreshz'
		source =
				let
				    Source = Value.NativeQuery(Snowflake.Databases("vena-prod.snowflakecomputing.com","PRODUCT_POWER_USER_READ_WH",[Implementation="2.0"]){[Name="PROD_HARMONIZED"]}[Data], "WITH prod_tenant_list AS (#(lf)    SELECT DISTINCT tenant_id#(lf)    FROM PROD_HARMONIZED.PRODUCT.TENANT_PROF#(lf)    WHERE crnt_rcrd_ind = 'Y'#(lf)      AND tenant_typ_nm IN ('PRODUCTION', 'SANDBOX')#(lf)      AND organization_typ_nm = 'CUSTOMER'#(lf)      AND tenant_enbld_status_nm = 'ENABLED'#(lf)),#(lf)#(lf)simple_refreshes AS (#(lf)    SELECT#(lf)        h.tenant_id,#(lf)        h.user_id,#(lf)        CAST(h.timing_val AS FLOAT)                   AS timing_val,#(lf)        DATE_TRUNC('MONTH', h.session_start_dts)      AS year_month#(lf)    FROM PROD_HARMONIZED.PRODUCT.HYDRA_UI_ACTIONS h#(lf)    INNER JOIN prod_tenant_list t#(lf)        ON h.tenant_id = t.tenant_id#(lf)    WHERE h.event_nm      ILIKE '%simplerefresh%'#(lf)      AND h.timing_ctgry_nm = 'DesktopAddin'#(lf)      AND TO_DATE(h.session_start_dts) >= CURRENT_DATE - 365#(lf))#(lf)#(lf)SELECT#(lf)    year_month,#(lf)    COUNT(*)                                                         AS total_refreshes,#(lf)    COUNT(CASE WHEN timing_val <= 8 THEN 1 END)                     AS refreshes_below_8s,#(lf)    ROUND(#(lf)        COUNT(CASE WHEN timing_val <= 8 THEN 1 END)::FLOAT#(lf)        / NULLIF(COUNT(*), 0), 4#(lf)    )                                                                AS pct_below_8s,#(lf)    ROUND(AVG(timing_val), 4)                                        AS avg_timing,#(lf)    ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY timing_val), 4) AS p25_timing,#(lf)    ROUND(PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY timing_val), 4) AS p50_timing,#(lf)    ROUND(PERCENTILE_CONT(0.70) WITHIN GROUP (ORDER BY timing_val), 4) AS p70_timing,#(lf)    ROUND(PERCENTILE_CONT(0.80) WITHIN GROUP (ORDER BY timing_val), 4) AS p80_timing,#(lf)    ROUND(PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY timing_val), 4) AS p90_timing,#(lf)    ROUND(PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY timing_val), 4) AS p95_timing,#(lf)    ROUND(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY timing_val), 4) AS p99_timing,#(lf)    COUNT(DISTINCT tenant_id)                                        AS distinct_tenants,#(lf)    COUNT(DISTINCT user_id)                                          AS distinct_users#(lf)FROM simple_refreshes#(lf)GROUP BY year_month#(lf)ORDER BY year_month", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YEAR_MONTH", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

