table 'Desktop Add-in Version Usage'
	lineageTag: 24dfe40a-0201-4d5a-bbc6-08fea360e0c7

	measure 'calls per month' = calculate(count('Desktop Add-in Version Usage'[REQUEST_END_DATE]),PARALLELPERIOD('Date Table'[End of Month],0,MONTH))
		formatString: #,0
		lineageTag: 12993f33-9d62-4059-99e1-dadac9527af0

	measure 'test ratio' = [# of 2022 versions]/[calls per month]
		formatString: #,0
		lineageTag: d61412f5-a64a-4a23-886b-0a296a3a1808

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '# of 2022 versions' =
			calculate(
			
			    count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2022-02-01")
		formatString: #,0
		lineageTag: b32255ea-e6af-4113-9cc3-0636e2d34d3a

	measure 2019-02-01 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2019-02-01"),[calls per month])
		formatString: #,0
		lineageTag: 53c78f0e-1a92-4114-b8a2-0491044f0ffb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2020-02-01 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2020-02-01"),[calls per month])
		formatString: #,0
		lineageTag: b383248c-9e2b-4a82-837c-a3ab5acb1e58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2021-02-01 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2021-02-01"),[calls per month])
		formatString: #,0
		lineageTag: 1d468e14-2a39-4319-8212-fd8af02f31c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2022-02-01 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2022-02-01"),[calls per month])
		formatString: #,0
		lineageTag: eae7f4ee-c720-4db1-ab37-4c5e7018f931

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-02-15 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-02-15"),[calls per month])
		formatString: #,0
		lineageTag: 278d22ce-8cc3-4ca5-a43a-47f3cbb98db0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-05-31 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-05-31"),[calls per month])
		formatString: #,0
		lineageTag: 2261e5a4-e511-43ac-99c9-cf9a38d22c20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-06-13 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-06-13"),[calls per month])
		formatString: #,0
		lineageTag: 0e666a37-02fc-411e-941e-d7900e980dca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-07-12 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-07-12"),[calls per month])
		formatString: #,0
		lineageTag: 3f6340d8-aaa7-4e84-b59c-e0d35f8e1255

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-08-15 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-08-15"),[calls per month])
		formatString: #,0
		lineageTag: 73b88719-fa60-4ea4-8989-69e74d843f7b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-10-04 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-10-04"),[calls per month])
		formatString: #,0
		lineageTag: bdca6d21-df4a-44ac-8a6a-90997c69b6fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-10-10 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-10-10"),[calls per month])
		formatString: #,0
		lineageTag: 7f3fdb5e-d7f4-4349-86bc-0540685d59d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2023-10-24 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2023-10-24"),[calls per month])
		formatString: #,0
		lineageTag: ec964034-6b52-4e53-8acc-a7137f23712a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-02-26 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-02-26"),[calls per month])
		formatString: #,0
		lineageTag: 4987097c-bd3b-4294-a90f-ccd9a2c82668

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-03-21 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-03-21"),[calls per month])
		formatString: #,0
		lineageTag: 96d5f13a-93bc-4cbb-a862-d7f9d7449d13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-05-01 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-05-01"),[calls per month])
		formatString: #,0
		lineageTag: 2f497535-ee58-48a6-ad7d-75d4d970ae77

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-06-10 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-06-10"),[calls per month])
		formatString: #,0
		lineageTag: 4064864c-1436-4334-8461-f50422916216

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-09-09 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-09-09"),[calls per month])
		formatString: #,0
		lineageTag: 4e4c738b-30b0-4711-9810-f6354304d7b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-09-17 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-09-17"),[calls per month])
		formatString: #,0
		lineageTag: d34b83fb-ae76-4e8a-8330-47a6ed1bc6c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 2024-10-08 =
			
			divide(calculate(count('Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS]), 'Desktop Add-in Version Usage'[INCREMENTAL_RELEASE_DATE_VERSIONS] = "2024-10-08"),[calls per month])
		formatString: #,0
		lineageTag: eb14967d-0479-4a7c-8829-f66476b4cd80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TENANT_ID
		dataType: string
		lineageTag: d807a80a-b569-4201-b536-63cc14bba625
		summarizeBy: none
		sourceColumn: TENANT_ID

		annotation SummarizationSetBy = Automatic

	column TENANT_NM
		dataType: string
		lineageTag: f14294db-6bd6-4115-8764-78a0ce802bc4
		summarizeBy: none
		sourceColumn: TENANT_NM

		annotation SummarizationSetBy = Automatic

	column INCREMENTAL_RELEASE_DATE_VERSIONS
		dataType: string
		lineageTag: 288c1548-57f8-459f-a350-ff8298c34c87
		summarizeBy: none
		sourceColumn: INCREMENTAL_RELEASE_DATE_VERSIONS

		annotation SummarizationSetBy = Automatic

	column USER_ID
		dataType: string
		lineageTag: 70220404-8b17-4206-9848-fb6e447a084c
		summarizeBy: none
		sourceColumn: USER_ID

		annotation SummarizationSetBy = Automatic

	column REQUEST_END_DATE
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 2a571532-9b5a-40e4-9d28-ad7a06975885
		summarizeBy: none
		sourceColumn: REQUEST_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LATEST_VERSION
		dataType: string
		lineageTag: 31d84088-e51d-4245-b660-4a4c5be3847e
		summarizeBy: none
		sourceColumn: LATEST_VERSION

		annotation SummarizationSetBy = Automatic

	partition 'Desktop Add-in Version Usage' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Snowflake.Databases("vena-prod.snowflakecomputing.com","PRODUCT_POWER_USER_READ_WH"){[Name="PROD_HARMONIZED"]}[Data], "WITH PROD_TENANT_INFO AS#(lf)(#(lf)select#(lf)tenant_id,#(lf)tenant_nm,#(lf)data_cntr_cd#(lf)from PROD_HARMONIZED.PRODUCT.TENANT_PROF#(lf)where CRNT_RCRD_IND = 'Y'#(lf)and tenant_typ_nm = 'PRODUCTION'#(lf)and tenant_enbld_status_nm = 'ENABLED'#(lf)),#(lf)#(lf)user_info as #(lf)(#(lf)SELECT distinct#(lf)substr(tenant_dc,charindex('.', tenant_dc)+1,len(tenant_dc)) as tenant_id,#(lf)user_id,#(lf)left(tenant_dc,3) as data_center#(lf)FROM PROD_HARMONIZED.PRODUCT.VW_USER_PROF#(lf)where crnt_rcrd_ind = 'Y'#(lf)and actvtn_status_nm = 'ACTIVE'#(lf)and (last_impersonation_login_dt is null and ntfctn_email is null)#(lf))#(lf)#(lf)#(lf)select#(lf)tenant_nm,#(lf)api.tenant_id,#(lf)api.user_id,#(lf)to_date(request_end_dts) as request_end_date,#(lf)substring(query_string,len(query_string)-13,9) as latest_version,#(lf)case #(lf)when substring(query_string,len(query_string)-13,9) >= 2024.1008 then '2024-10-08'#(lf)when substring(query_string,len(query_string)-13,9) >= 2024.0917 and substring(query_string,len(query_string)-13,9) < 2024.1008 then '2024-09-17'#(lf)when substring(query_string,len(query_string)-13,9) >= 2024.0909 and substring(query_string,len(query_string)-13,9) < 2024.0917 then '2024-09-09'#(lf)when substring(query_string,len(query_string)-13,9) >= 2024.0610 and substring(query_string,len(query_string)-13,9) < 2024.0909 then '2024-06-10' #(lf)when substring(query_string,len(query_string)-13,9) >= 2024.0501 and substring(query_string,len(query_string)-13,9) < 2024.0610 then '2024-05-01' #(lf)when substring(query_string,len(query_string)-13,9) >= 2024.0321 and substring(query_string,len(query_string)-13,9) < 2024.0501 then '2024-03-21'#(lf)when substring(query_string,len(query_string)-13,9) >= 2024.0226 and substring(query_string,len(query_string)-13,9) < 2024.0321 then '2024-02-26' #(lf)when substring(query_string,len(query_string)-13,9) >= 2023.1024 and substring(query_string,len(query_string)-13,9) < 2024.0226 then '2023-10-24'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.1010 and substring(query_string,len(query_string)-13,9) < 2023.1024 then '2023-10-10'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.1004 and substring(query_string,len(query_string)-13,9) < 2023.1010 then '2023-10-04'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.0815 and substring(query_string,len(query_string)-13,9) < 2023.1004 then '2023-08-15'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.0712 and substring(query_string,len(query_string)-13,9) < 2023.0815 then '2023-07-12'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.0613 and substring(query_string,len(query_string)-13,9) < 2023.0712 then '2023-06-13'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.0531 and substring(query_string,len(query_string)-13,9) < 2023.0613 then '2023-05-31'#(lf)when substring(query_string,len(query_string)-13,9) >= 2023.0215 and substring(query_string,len(query_string)-13,9) < 2023.0531 then '2023-02-15'#(lf)when substring(query_string,len(query_string)-13,9) >= 2022.0201 and substring(query_string,len(query_string)-13,9) < 2023.0215 then '2022-02-01'#(lf)when substring(query_string,len(query_string)-13,9) >= 2021.0201 and substring(query_string,len(query_string)-13,9) < 2022.0201 then '2021-02-01'#(lf)when substring(query_string,len(query_string)-13,9) >= 2020.0201 and substring(query_string,len(query_string)-13,9) < 2021.0201 then '2020-02-01'#(lf)when substring(query_string,len(query_string)-13,9) >= 2019.0201 and substring(query_string,len(query_string)-13,9) < 2020.0201 then '2019-02-01'#(lf)end as incremental_release_date_versions#(lf)#(lf)FROM PROD_HARMONIZED.PRODUCT.USER_API_ACTIVITY api#(lf)inner join prod_tenant_info on prod_tenant_info.tenant_id = api.tenant_id and prod_tenant_info.data_cntr_cd = api.data_cntr_cd#(lf)inner join user_info on user_info.tenant_id = api.tenant_id and user_info.user_id = api.user_id and user_info.data_center = api.data_cntr_cd#(lf)WHERE to_date(request_end_dts) > '2023-02-01'#(lf)and request_status_cd = '200'#(lf)and REQUEST_ENDPOINT_NM ilike '%/fsm/v2/%'#(lf)AND QUERY_STRING LIKE '%&addinVersion=1.20%'", null, [EnableFolding=true]),
				    #"Sorted Rows" = Table.Sort(Source,{{"LATEST_VERSION", Order.Descending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

