// Welcome to DAX query view! Learn more about DAX queries at https://aka.ms/dax-queries.
// Right-click on tables, columns, or measures in the data pane to access quick queries, or ask Copilot for help writing DAX.

// Select "Run" to try this sample DAX query.
DEFINE
MEASURE Agg_Hydra_SimpleRefresh_Tenant_Monthly[P70 (Weighted)] = 
    DIVIDE(
        SUMX(Agg_Hydra_SimpleRefresh_Tenant_Monthly,
            Agg_Hydra_SimpleRefresh_Tenant_Monthly[P70_TIMING] * Agg_Hydra_SimpleRefresh_Tenant_Monthly[REFRESH_COUNT]
        ),
        SUM(Agg_Hydra_SimpleRefresh_Tenant_Monthly[REFRESH_COUNT])
    )
